### ISSUE TITLE
Task 3. Create function to annotate epimutations results 

### ISSUE THREAD

**Issue by yocra3** [yocra3/epimutacions#14]
Add genomic annotation to epimutations detected. List of proposed features that can be added:

- [x] Proximal gene
- [x] Gene position (i.e. promoter, body, 5'UTR...)
- [x] OMIM entries for proximal gene
- [ ] pLI of proximal gene
- [x] CpG islands
- [ ] Imprinted regions
- [x] cRE: overlap with cis-regulatory elements from ENCODE
- [ ] chromatin state: overlap with chromatin states from ENCODE

**Comment by yocra3** [comment]
Reformat the issue in subtasks:

- [x] #36 Add illumina annotation
- [x] #37 Add OMIM data
- [ ] #38 Add gnomAD data
- [x] #39 Add ENSEMBL regulatory elements
