### ISSUE TITLE
Task 5. Document the functions

### ISSUE THREAD

**Issue by yocra3** [yocra3/epimutacions#17]
Add documentation to:

- [ ] `BumpBetaMatrix.R`
- [ ] `epiIsolationForest.R`
- [ ] `epiMahdist.R`
- [ ] `EpiMANOVA.R`
- [ ] `EpiMLM.R`
- [ ] `EpiMutations.R`
- [ ] New algorithm function - #12 
- [ ] Function of Barbosa algorithm - #10 
- [ ] Function to annotate epimutation - #14 
- [ ] Plotting functions - #16 and #15
