### ISSUE TITLE
Task 7. Add tests to functions

### ISSUE THREAD

**Issue by yocra3** [yocra3/epimutacions#20]
Define tests for the functions of our package:

- [ ] `BumpBetaMatrix`
- [ ] `epiIsolationForest`
- [ ] `epiMahdist`
- [ ] `EpiMANOVA`
- [ ] `EpiMLM`
- [ ] `EpiMutations`
- [ ] New algorithm function - #12 
- [ ] Function of Barbosa algorithm - #10 
- [ ] Function to annotate epimutation - #14 
- [ ] Plotting functions - #16 and #15
