### ISSUE TITLE
Task 11. Improve implementation of current algorithms

### ISSUE THREAD

**Issue by yocra3** [yocra3/epimutacions#24]
The following issues should be solved in `EpiMANOVA` function:

- [ ] #11 Modify `EpiMANOVA` to comply with Aref-Eshghi et al, 2020 
- [ ] #25 Export stastistic in `EpiMANOVA`
- [ ] #26 Check input in `EpiMANOVA`
