### ISSUE TITLE
Task 1. Improve main function `EpiMutation`

### ISSUE THREAD

**Issue by yocra3** [yocra3/epimutacions#4]
Implement enhancements and bugs of `EpiMutation` function:

- [x] #1 Allow using cases as reference
- [x] #2 User should be able to choose the reference panel
- [x] #3 Run epimutation discovery to all samples
- [ ] #6 Improve results reporting of EpiMutations
- [x] #7 Report empty results if no epimutations are found
- [ ] #8 Allow passing parameters to `EpiMutations` inner functions
- [ ] #13 Remove for loop in epimutations detection

**Comment by yocra3** [comment]
@james Can you change the default parameters for epimutations? Now, the default num.cpgs, which defines the smallest size we are considering is 10. This is quite big. Could you set it to 3? Once this and the genomicratioset from Pavlo are changed, the examples can be run using default parameter values.

**Comment by jamesbaye** [comment]
Sure, see #61
