### ISSUE TITLE
Improve implementation of main function `EpiMutation`

### ISSUE THREAD

**Issue by yocra3** [yocra3/epimutacions#5]
Implement enhancements and bugs of `EpiMutation` function:

- [ ] #1 Allow using cases as reference
- [ ] #2 User should be able to choose the reference panel
- [ ] #3 Run epimutation discovery to all samples
